# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('stage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('discharge', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ISCO', models.BooleanField()),
                ('voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
    ]
