# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0007_remove_sample_site'),
        ('stagerecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerecord',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitelog.Site'),
            preserve_default=False,
        ),
    ]
