# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateTimeField(verbose_name='collection date')),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('tape_down', models.FloatField(blank=True, null=True)),
                ('logger_stage', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('samples_taken', models.IntegerField(default=0)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sitelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelog.SiteLog'),
        ),
    ]
