# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateTimeField(verbose_name='collection date')),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(verbose_name='date published')),
                ('samples_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sitelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelog.SiteLog'),
        ),
    ]
