# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelog',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitelog',
            name='logger_stage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitelog',
            name='personnel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitelog',
            name='tape_down',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
