# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0002_sitelog_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('waterbody_name', models.CharField(max_length=100)),
                ('parent_waterbody', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('road', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
