# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0003_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='sitelog.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='box_rp_elevation',
            field=models.DecimalField(blank=True, decimal_places=3, default=199, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='d2w',
            field=models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='ip_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='isws_station_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='land_owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='modem_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='modem_sn',
            field=models.BigIntegerField(blank=True, default=10012),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='nearest_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='offset',
            field=models.DecimalField(blank=True, decimal_places=3, default=12, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='rp_elevation',
            field=models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='zipcode',
            field=models.IntegerField(blank=True, default=61820),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='site',
            name='parent_waterbody',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='road',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='waterbody_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitelog',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelog.Site'),
        ),
    ]
