# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0005_auto_20160119_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
