# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0006_site_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='site',
        ),
    ]
