# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelog', '0007_remove_sample_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
